site_name: MKNews Tech Digest
site_url: https://DEmodoriGatsuO.github.io/MKNews/
site_description: 'A comprehensive digest of AI technology news and trends'
site_author: 'Your Name'
repo_name: 'DEmodoriGatsuO/MKNews'
repo_url: 'https://github.com/DEmodoriGatsuO/MKNews'

# Navigation
nav:
  - Home: index.md
  - News Feed:
    - Overview: news/index.md
  - Archive:
    - '2025-05': archive/2025-05.md
  - About: about.md

# Theme Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      title: On this page

plugins:
  - search
  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DEmodoriGatsuO